[build]
  command = "bash netlify-build.sh"
  publish = "build"

[[headers]]
  for = "/assests/*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Accept-Ranges = "bytes"

[[headers]]
  for = "/assests/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
